// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jefofujjcqwblavoybfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZm9mdWpqY3F3Ymxhdm95YmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjE0MjgsImV4cCI6MjA2NjA5NzQyOH0._Wei4LC6wfXFcjrmoz7UfZf0l0Y_WjPjdWjHyC26QaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});